apiVersion: v1
kind: Service
metadata:
  name: apache-multi-svc
spec:
  type: {{ .Values.services.type }}
  selector:
    app: apache-multi
  ports:
    - name: service1
      port: {{ .Values.services.service1.port }}
      targetPort: {{ .Values.services.service1.targetPort }}
      nodePort: {{ .Values.services.service1.nodePort }}
    - name: service2
      port: {{ .Values.services.service2.port }}
      targetPort: {{ .Values.services.service2.targetPort }}
      nodePort: {{ .Values.services.service2.nodePort }}
 